apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: green
  template:
    metadata:
      labels:
        environment: green
    spec:
      containers:
      - name: my-nginx
        image: my-nginx:latest
        ports:
        - containerPort: 80
