apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  selector:
    environment: blue
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancerspec:
  selector:
    environment: blue
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
